name: Container Actions


on:
  workflow_dispatch:


jobs:
  python-dockerfile:
    runs-on: ubuntu-latest
    name: Python Container Action
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - name: Run container action
        uses: ./.github/actions/container-action
        id: hello
        with:
          who-to-greet: "from a container github action ðŸ‘‹"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
