name: Test JS Build Action

on:
  workflow_dispatch:


jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/actions/js-build-action
      - uses: vlad-yarko/js-build-action@v2.0.0
      # - uses: vlad-yarko/js-build-action@v1.0.0
        with:
          name: "Puppy"
