name: Messages


on:
  workflow_dispatch:


jobs:
  log-at-various-levels:
    runs-on: ubuntu-24.04
    steps:
      - name: Echo some things
        run: |
          echo "::debug::This is a debug message"
          echo "::info::This is an info message"
          echo "::warning::This is an warning message"
