name: Puppy workflow matrix


on:
  workflow_dispatch:


jobs:      
  puppy-1:
    strategy:
      matrix:
        name: [biba, boba]
        dick: [small, huge]
    runs-on: ubuntu-24.04
    name: Puppy workflow matrix job
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - id: composite-action-instance
        uses: ./.github/actions/puppy-action
        with:
          puppy-name: ${{ matrix.name }}
          puppy-dick: ${{ matrix.dick }}
      - env:
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.puppy-random-number }}
        run: echo random-number "$RANDOM_NUMBER"
        shell: bash
